Use settings classes
indrajithi/tiny-web-crawler pull request #48
Opened 2024-06-19 20:21 UTC by Mews

Closes #46 

**Changes**
- Added the `core/settings` submodule with the `GeneralSettings` and `CrawlSettings` classes that store options for the `Spider` class;
- Made the `settings` submodule importable from the main module;
- Changed the `Spider` class to use the settings classes;
- Changed the docstring for the `Spider` class;
- Changed the tests to setup spiders with the new settings classes;
- Updated the usage example in the README;

2024-06-20 14:58 UTC, indrajithi commented on README.md
> +
Let us give an example on how to change the crawl settings.

2024-06-20 16:16 UTC, indrajithi requested changes

2024-06-20 16:16 UTC, indrajithi commented on src/tiny_web_crawler/core/settings.py
> +            raise ValueError("Only one of internal_links_only and external_links_only can be set to True")
We can consolidate the settings into one class and avoid the need to manage multiple settings instances.
Introduce a new settings class that inherits from both these classes. And use it in in Spider class


```Python
In [71]: from dataclasses import dataclass, field
    ...: from typing import Optional
    ...:
    ...: @dataclass
    ...: class GeneralSettings:
    ...:     root_url: str = '/'
    ...:     max_links: int = 5
    ...:     save_to_file: Optional[str] = None
    ...:     max_workers: int = 1
    ...:     delay: float = 0.5
    ...:     verbose: bool = False
    ...:
    ...: @dataclass
    ...: class CrawlSettings:
    ...:     url_regex: Optional[str] = None
    ...:     include_body: bool = False
    ...:     internal_links_only: bool = False
    ...:     external_links_only: bool = False
    ...:     respect_robots_txt: bool = True
    ...:
    ...: @dataclass
    ...: class SpiderSettings(GeneralSettings, CrawlSettings):
    ...:     pass
    ...:

```
And we can use it as composition in Spider class

```python

@dataclass
    class Spider:
        settings: SpiderSettings

settings = SpiderSettings(root_url="https://pypi.org/", verbose=True)
s = Spider(settings)

s.settings.root_url
'https://pypi.org/'


In [26]: s = Spider(settings)

In [27]: s.settings.root_url
Out[27]: 'https://pypi.org/'
```
This way we only need to manage one Settings class and the attributes are in separate classes.
Also when initializing we need not call multiple classes to set the attributes. 

And in our code we can use `settings.max_links and settings.include_body`  instead of `general_settings.max_links`

We need to provide a default value for everything or make it optional. We can also add `(kw_only=True)` to `GeneralSettings` instead. But it is only supported in python > 3.10.

So let us add a default value for root_url for this to work (everything else has a default value).

2024-06-20 16:16 UTC, indrajithi commented on src/tiny_web_crawler/core/settings.py
> +            raise ValueError("Only one of internal_links_only and external_links_only can be set to True")
And we can rename the file as `spider_settings.py`

2024-06-21 08:29 UTC, Mews commented on src/tiny_web_crawler/core/settings.py
> +            raise ValueError("Only one of internal_links_only and external_links_only can be set to True")
Done!

2024-06-21 11:01 UTC, indrajithi approved these changes

2024-06-21 11:01 UTC, merged